apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: jenkins-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      imagePullSecrets:
        - name: nexus-regcred
      securityContext:
        runAsNonRoot: true
      containers:
        - name: flask-app
          image: nexus:8082/jenkins-lab/flask-app:placeholder
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: placeholder
          readinessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits: { cpu: 250m, memory: 256Mi }
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities: { drop: ["ALL"] }
